### ISSUE TITLE
Joplin-desktop erroneously reporting expired certificate

### ISSUE THREAD

**Issue by mattcaron** [MrCarroll/joplin-desktop-snap#17] opened 2021-10-01 01:34 UTC
Greetings!

I believe this is the correct place to report the issue. If not, I apologize for wasting your time.

For some reason, possibly (but not certainly) related to https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/, as of 30 September, 2021, Joplin Desktop now refuses to sync with my Nextcloud instance, which uses a LetsEncrypt cert. Note that standard browsers (Firefox, Chrome) and Mail clients (Thunderbird) as well as the Android Joplin client don't have an issue with the certificate on this server - only the joplin-desktop snap.

I speculate that it is a root CA issue, but I could be wrong.

I believe we need to ensure that `/etc/ssl/certs/ISRG_Root_X1.pem` exists. I would expect it to, because it is in `core20`, which I see the snap uses.

Thanks in advance.

Edit: If I tick "Ignore TLS certificate errors", I can force it to work, but this is suboptimal for normal operation.

**Comment by JGCarroll** [comment] 2021-10-01 02:03
Hello, and thanks for the report :)

Electron applications embed and use their own copy of Mozilla's CA bundle rather than the usual system store, and it's this bundle that's causing the problem. Unfortunately it's a rather severe problem effecting essentially every Electron application currently deployed.

There's some other issues you might be interested in reading

https://github.com/laurent22/joplin/issues/5513
https://github.com/electron/electron/issues/31212 (This also has a workaround you can use on the server generating a new certificate with a different chain, which you might consider rather than disabling the certificate checking in the app itself).

For the time being, the fix is to wait for Electron to release new builds, wait on Joplin upstream to rebase on a newer Electron version (Currently on version 10, at a minimum Joplin would have to jump to version 12), and for me to rebuild the snap for the new release.

I've no idea how long it'll take Joplin to rebase the Electron dependency but the patched Electron builds should be fairly quick and I'll try be alert to when I need to do my part.

I'll post back here when there's a new revision of the snap that fixes this problem.

Cheers

**Comment by benmordecai** [comment] 2021-10-01 03:15
Based on electron/electron#31212 this should be released now, right?

**Comment by mattcaron** [comment] 2021-10-01 03:18
That all makes perfect sense. Thank you for the explanation.

My only reply would be a sad trombone sound.

I figured it was localized to the snap - a missing dependency or something. The fact that it affects *all* electron apps is... disconcerting.

**Comment by JGCarroll** [comment] 2021-10-01 03:48
> 
> 
> Based on [electron/electron#31212](https://github.com/electron/electron/issues/31212) this should be released now, right?

Electron upstream has only rebuilt versions 12 through 16.

If Joplin was already on Electron 12 or greater it'd have been a trivial rebuild involving just bumping the version number in the package list, but it's on version 10 which is EOL, unfortunately Electron applications being held back several versions is fairly common in the ecosystem.

Joplin did attempt to upgrade to Electron 12 a few months ago so there's prior work that might speed it up, but at the same time, the reason it isn't already on Electron 12 is because there was roadblocks too, so I've no real insight into how long it might take because it's a complex upgrade and I'm only involved in packaging it.

**Comment by q-wertz** [comment] 2021-10-19 12:20
Here is the original Joplin issue: https://github.com/laurent22/joplin/issues/5513

You can either `Ignore TLS certificate errors` or wait till version >2.5.1 (https://github.com/laurent22/joplin/issues/5513#issuecomment-932934097).

**Comment by JGCarroll** [comment] 2021-10-31 14:54
The Joplin 2.5.8 has been marked as stable upstream and fixes this bug. Since it also introduces a regression with some of the GTK file dialogs, I'm going to try and workaround them first, but otherwise I'll push 2.5.8 within a few days at max.

**Comment by JGCarroll** [comment] 2021-11-01 03:24
The 2.5.8 snap is rolling out now and should fix this issue.

**Closed as completed by JGCarroll** 2021-11-01 03:24 UTC
