### ISSUE TITLE
Contact to Joplin developers

### ISSUE THREAD

**Issue by onlygecko** [MrCarroll/joplin-desktop-snap#1] opened 2020-06-01 18:47 UTC
He,

it's great to see, that someone managed to create a snap of Joplin! Congrats! :+1: 

I have two questions regarding the snap:
* Have You  already contacted the Joplin developers to integrate the build configuration?
* What steps are necessary to publish a new Joplin version? Is a new tag automatically detected or do You have to change the tag name manually?

Thanks again for Your work!

Greetings,
Peter

**Comment by JGCarroll** [comment] 2020-06-01 20:45
I haven't been in touch with Joplin upstream yet. I wanted to see if the Snap actually works to peoples expectations first before pushing on potentially unwanted maintenance to upstream. It seems to be picking up traction though pretty rapidly, so it might be worth getting in touch with them sooner than I'd have done otherwise because it's hard to transition users from one Snap package to another (I.E, from joplin-james-carroll to just joplin; unfortunately the joplin name is reserved and requires going through an authentication process with Canonical to be able to push to it, which is why I didn't claim that name instantly and just transfer the ownership over instead).

Publishing a new version in the specific environment this repo is in now is a manual affair by which I increment the version number tag (which is entirely to avoid pre-release tags and might have a workaround I haven't considered yet) and run Snapcraft on my own machine and upload it to the store manually. Improvements could be:

- If Snap is seen as a suitable format upstream, the contents of this repo could just be dropped in the master upstream build with minor changes, and then use the Canonical Snapcraft build service, which integrates with Github webhooks, to automatically build and publish the Snap packages for every commit
- Have a Github CI runner run on a schedule, and trigger that webhook manually if it detects new releases, achieving nearly the same effect if the snap build files are seperated from the master repo.

So, the entire process could be automated but for now I'm happy pushing myself on every major releases since it's not very much effort.

I'll drop a message on their GitHub later this week to see if they'd be interested in carrying Joplin as a Snap officially and if so I'll hide the one vendored to my name from the store results.

**Comment by onlygecko** [comment] 2020-06-03 19:32
Thank You that you took the time to respond in such a detailed way. 😀

Please let me know if I can help you in any way. I have the snap currently running on two machines (Ubuntu 20.04) without any errors (and syncing via Nextcloud). 👍

Greetings,
Peter

**Comment by JGCarroll** [comment] 2020-06-04 11:31
Thanks for the offer, if you have any Snap specific bug reports, reporting them would be a huge help!

I've spent the past few hours working on getting some automated infrastructure going. Weekly, Github will run a script that checks the latest Joplin release. If it finds a new non pre-release release, it'll push a commit to this repo changing the source-tag value, and that commit will trigger the Canonical hosted Snapcraft build servers into packaging and automatically releasing a new snap on the edge channel. So at worst, the edge channel shouldn't ever be more than a week out of date vs the upstream package. If you're bothered about keeping up to date on high cadence, the edge channel is for you (but I'd be careful using it with other snaps, as it's meant to be highly experimental generally speaking). Since that's all handled magically now, it becomes the click of a button for me to promote that into stable and every one would get it, but that's still manual for now.

You may have noticed I posted on the Joplin forums after your own post there, so if the upstream devs are interested in making a Joplin snap more official, they have what they need for an informed decision. 

Thanks for all your kindness!
I'll close this issue down now, but as I say, if you have any bug reports or other general issues in the future feel free to get in touch.

**Closed as completed by JGCarroll** 2020-06-04 11:31 UTC

**Comment by JGCarroll** [comment] 2020-06-08 09:06
Just as an update if you're curious, Laurent has been in touch with me and there is some interest in possibly upstreaming Snap as an officially supported platform, subject to it recieving feedback to see if it infact a suitable platform first; in the future, there may just be an actual "Joplin" package in the Snap store, but there's no absolutes yet.

**Comment by 3v1n0** [comment] 2021-04-19 11:46
Hey, any update on this?

Would  be nice to have it officially supported (including the terminalapp too) :)

**Comment by JGCarroll** [comment] 2021-04-19 13:49
At the moment, the Flatpak/Snap packages are still unlikely to ever be officially supported. The sandboxing introduces regressions vs the unconfined AppImage and whilst the majority of people won't ever notice them, it does come up from time to time for users.

Practically, I'm not sure being officially supported would make much difference. I think it's long been at the point where all the defects are caused by being Snap/Flatpak to begin with, there's not much I can honestly think of that would change if the support was official. 

Hypothetically if Snapcraft allowed Joplin to become an unconfined classic Snap I could see the situation changing, but can't happen for policy reasons and would so would need to be distributed outside the Snap store, which basically makes it on par with the AppImage but not particularly better than it. Obsidian does use this model, and some people do use it, but I can't imagine it's many.

I might take a look at the Joplin terminal in the future, but support wise it'd still be unofficial.

**Comment by 3v1n0** [comment] 2021-04-19 21:59
> I might take a look at the Joplin terminal in the future, but support wise it'd still be unofficial.

On terminal side, I've prepared it: https://snapcraft.io/joplin-cli/ (https://github.com/3v1n0/joplin-cli-snap)

I've used the `cli` name, but to match upstream would be better to use `joplin`, do you own it maybe?

**Comment by JGCarroll** [comment] 2021-04-19 22:42
I do have both `joplin` and `joplin-terminal`

Personally for consistency purposes, I think ideally `joplin-terminal` is the better option and it might make more sense to use `joplin-terminal` and request automatic aliasing so it's accessible as `joplin` too, I think you'd likely be granted it considering it makes sense with the split between the packages. `terminal` is how upstream and other repo's refer to it too.

Regardless, would you like me to send you a request to the email attached to your Github account or do you have an alternate address? Feel free to email me if you'd like to keep it hidden.

**Comment by 3v1n0** [comment] 2021-04-19 22:47
> Personally for consistency purposes, I think ideally `joplin-terminal` is the better option and it might make more sense to use `joplin-terminal` and request automatic aliasing so it's accessible as `joplin` too, I think you'd likely be granted it considering it makes sense with the split between the packages.

Yeah, I was thinking to the same, but then I saw that upstream used just `joplin` naming, but indeed we can use aliasing too. The reason for it, to me was mostly the possibility of using it as a service for having a web and alternate interfaces too, so this the reason I liked more the pure `joplin` name as having `joplin.service` made some sense.

> Regardless, would you like me to send you a request to the email attached to your Github account or do you have an alternate address? Feel free to email me if you'd like to keep it hidden.

Github one is used in snapcraft.io as well, thanks!

**Comment by JGCarroll** [comment] 2021-04-19 23:00
`joplin-server` is currently WIP upstream and is targetted to have a web GUI for editing notes and collaboration and such, so the naming would end up being more confusing when that releases officially, I'd be inclined to agree with you `joplin.service` looks better, but given it's a matter of when, not if; I'd say it's probably the best option overall.

I've sent the collaboration request off now and I'll put a post for full ownership transfer in the forums once it's accepted :).

**Comment by 3v1n0** [comment] 2021-04-20 00:58
> `joplin-server` is currently WIP upstream and is targetted to have a web GUI for editing notes and collaboration and such, so the naming would end up being more confusing when that releases officially

I think there's some confusion here with the terms used, in fact [the `joplin-server` you're referring to](https://discourse.joplinapp.org/t/joplin-server-pre-release-is-now-available/13605) (I think) is something that should be used only for notes syncing, while the `joplin server` I refer to, is the _clipper server_ that is the one which provides the [REST API](https://joplinapp.org/api/references/rest_api/) for implementing other applications.

And that's currently provided via the same `cli` client when using `joplin server start`.
